# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '08:00'
      timezone: 'Europe/Madrid'
    labels:
      - 'dependencies'
    allow:
      - dependency-type: 'all'
    commit-message:
      prefix: 'npm prod'
      prefix-development: 'npm dev'
      include: 'scope'
